name: CI

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=BRANCH_NAME;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: Test PR
      if: ${{ env.BRANCH == 'master' }}
      run: echo 'success'
      env: 
        BRANCH: echo ${{ steps.extract_branch.outputs.BRANCH_NAME }}
 
