name: CI

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: echo
      run: |
        echo "${{ github.event_name }}"
        echo "${{ github.event.action }}"
        echo "${{ github.event.pull_request.merged }}"
        echo "${{ github.base_ref }}"
      
    - name: Test pull request
      if: github.event_name == 'push' && github.base_ref == 'refs/heads/master'
      run: |
        echo "${{ github.event_name }}"
        echo "${{ github.base_ref }}"
