name: CI

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: echo
      run: |
        echo "${{ github.event_name }}"
        echo "${{ github.event.action }}"
        echo "${{ github.event.pull_request.merged }}"
        echo "${{ github.base_ref }}"
      
    - name: Test PR
      if: github.event.pull_request.merged
      run: echo "${{ github.event_name }}"
