name: CI

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=BRANCH_NAME;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: Test PR
      run: |
        echo ::set-env name=BRANCH::$(echo $GITHUB_REF)
        echo $BRANCH
 
