name: CI

on: 
  schedule:
    - cron: "* * * * *"
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo $GITHUB_BASE_REF
      id: extract_branch
      
    - name: Test PR
      if: ${{ github.base_ref == 'master' }}
      run: |
        echo ::set-env name=BRANCH::$(echo $GITHUB_REF)
        echo ${{ env.BRANCH }}
 
