name: CI

on: [push, pull_request]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: echo
      run: |
        echo "${{ GITHUB_REF#'refs/heads/' }}"
      
    - name: Test PR
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: echo "success"
 
